### PR TITLE
chore: update to @sinet/coding-convetions 2.x

### PR DESCRIPTION
**Pull request by nyan2x**
Closes [TK-09200](https://www12.v1host.com/SchoolImprovementNetwork47/Task.mvc/Summary?oidToken=Task%3A96555&RoomContext=TeamRoom%3A1869)

### CODE REVIEW

**Comment by nyan2x** [comment]
@sydcanem @yamii can you guys take a quick look at this please? thanks!

**Comment by sydcanem** [comment]
:+1:

**Comment by openam** [comment]
We should probably release this as version 2.0.0, since it's not compatible with node < 4. https://github.com/School-Improvement-Network/lapin-send-error/blob/dev/package.json#L3

**Comment by nyan2x** [comment]
Got it. Thanks @openam.

**Comment by sydcanem** [comment]
@openam But that should be handled by a `bump` commit (including tagging the version) right?

**Comment by openam** [comment]
Yes typically we do a release commit, like in lapin https://github.com/sinet/lapin/commits/master

**Comment by yamii** [comment]
OK 👍

**Pull request merged**
